POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "krahljustus@gmail.com",
  "password": "SY&EgDLA2tA%b%%$4MJg"
}

> {%
    client.global.set("token", response.body.data.token);
    client.global.set("requesterToken", response.body.data.token);
%}
