### Registrieren (Auth)
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "email": "justus.krahl@digits.schwarz",
  "password": "WC7KALHkNBdQswm#",
  "firstName": "Max",
  "lastName": "Mustermann",
  "phone": "+49 123 456789",
  "birthDate": "1990-05-15",
  "emergencyContact": "+49 987 654321",
  "bio": "Ich liebe Haustiere und bin ein erfahrener Pet-Sitter",
  "role": "HOST",
  "postalCode": "68159",
  "city": "Mannheim",
  "acceptedPetSpecies": ["DOG", "CAT"]
}

> {%
    client.global.set("token", response.body.data.token);
    client.global.set("hostToken", response.body.data.token);
%}

###
