### Login (Auth)
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "justus.krahl@digits.schwarz",
  "password": "WC7KALHkNBdQswm#"
}

> {%
    client.global.set("token", response.body.data.token);
    client.global.set("hostToken", response.body.data.token);
%}



###
