### Registrieren (Auth)
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "email": "max.mustermann@example.com",
  "password": "SecurePhrase123!",
  "firstName": "Max",
  "lastName": "Mustermann",
  "phone": "+49 123 456789",
  "birthDate": "1990-05-15",
  "emergencyContact": "+49 987 654321",
  "profilePicture": "https://example.com/profile.jpg",
  "bio": "Ich liebe Haustiere und bin ein erfahrener Pet-Sitter",
  "role": "HOST",
  "postalCode": "68159",
  "city": "Mannheim",
  "acceptedPetSpecies": ["DOG", "CAT"]
}

> {%
    client.global.set("token", response.body.data.token);
%}

###
