CREATE TABLE IF NOT EXISTS users (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email VARCHAR(255) NOT NULL UNIQUE,
	password_hash VARCHAR(255) NOT NULL,
	first_name VARCHAR(255) NOT NULL,
	last_name VARCHAR(255) NOT NULL,
	phone VARCHAR(255) NOT NULL,
	birth_date DATE NOT NULL,
	emergency_contact VARCHAR(255) NOT NULL,
	profile_picture VARCHAR(255) NOT NULL,
	bio VARCHAR(255) NOT NULL,
    rating DOUBLE PRECISION,
    number_of_ratings INTEGER,
	role VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS pet (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	species VARCHAR(255),
	breed VARCHAR(255) NOT NULL,
	age INTEGER NOT NULL,
	special_needs VARCHAR(255) NOT NULL,
	owner_id BIGINT NOT NULL,
	CONSTRAINT fk_pet_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS request (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	pet_owner_id BIGINT NOT NULL,
	pet_id BIGINT NOT NULL,
	start_date DATE NOT NULL,
	end_date DATE NOT NULL,
	description VARCHAR(255) NOT NULL,
	location VARCHAR(255) NOT NULL,
	housing_type VARCHAR(255) NOT NULL,
	extras VARCHAR(255) NOT NULL,
	special_needs VARCHAR(255) NOT NULL,
	price VARCHAR(255) NOT NULL,
	status VARCHAR(255),
	CONSTRAINT fk_request_owner FOREIGN KEY (pet_owner_id) REFERENCES users (id),
	CONSTRAINT fk_request_pet FOREIGN KEY (pet_id) REFERENCES pet (id)
);

INSERT INTO users (email, password_hash, first_name, last_name, phone, birth_date, emergency_contact, profile_picture, bio, rating, number_of_ratings, role)
VALUES ('anna.meier@example.com', '$2a$10$7EqJtq98hPqEX7fNZaFWoOQxD9jQ2b6K8wF5gQd0mL5m8uM4uQx6K', 'Anna', 'Meier', '01711234567', '1994-03-12', 'Peter Meier', 'anna.png', 'Tierfreundin mit viel Hundeerfahrung.', 0.0, 0, 'PET_OWNER');

INSERT INTO users (email, password_hash, first_name, last_name, phone, birth_date, emergency_contact, profile_picture, bio, rating, number_of_ratings, role)
VALUES ('lukas.schmidt@example.com', '$2a$10$7EqJtq98hPqEX7fNZaFWoOQxD9jQ2b6K8wF5gQd0mL5m8uM4uQx6K', 'Lukas', 'Schmidt', '01721234567', '1991-08-05', 'Maria Schmidt', 'lukas.png', 'Aktiver Tiersitter fuer Wochenendbetreuung.', 0.0, 0, 'HOST');

INSERT INTO users (email, password_hash, first_name, last_name, phone, birth_date, emergency_contact, profile_picture, bio, rating, number_of_ratings, role)
VALUES ('sara.wagner@example.com', '$2a$10$7EqJtq98hPqEX7fNZaFWoOQxD9jQ2b6K8wF5gQd0mL5m8uM4uQx6K', 'Sara', 'Wagner', '01731234567', '1997-11-21', 'Tom Wagner', 'sara.png', 'Katzenliebhaberin und flexibel verfuegbar.', 0.0, 0, 'PET_OWNER');

INSERT INTO pet (name, species, breed, age, special_needs, owner_id)
VALUES ('Bello', 'DOG', 'Labrador', 4, 'Keine', (SELECT id FROM users WHERE email = 'anna.meier@example.com'));

INSERT INTO pet (name, species, breed, age, special_needs, owner_id)
VALUES ('Minka', 'CAT', 'Europaeisch Kurzhaar', 2, 'Braucht taeglich Medikamente', (SELECT id FROM users WHERE email = 'sara.wagner@example.com'));

INSERT INTO pet (name, species, breed, age, special_needs, owner_id)
VALUES ('Rocky', 'DOG', 'Mischling', 7, 'Etwas aengstlich bei Gewitter', (SELECT id FROM users WHERE email = 'anna.meier@example.com'));

INSERT INTO pet (name, species, breed, age, special_needs, owner_id)
VALUES ('Kiwi', 'BUDGIE', 'Wellensittich', 1, 'Kaefig nachts abdecken', (SELECT id FROM users WHERE email = 'lukas.schmidt@example.com'));
